export const loveMessages = [
  "You make my heart skip a beat.",
  "Every moment with you feels magical.",
  "You're my sunshine on a cloudy day.",
  "Loving you is my favorite adventure.",
  "You complete me in every way.",
  "You are my forever and always.",
  "With you, every day is Valentine's Day.",
  "I fall in love with you more each day.",
  "You light up my world like nobody else.",
  "My heart beats only for you.",
  "You're the reason I believe in love.",
  "Being with you feels like home.",
  "You're the sweetest part of my life.",
  "I cherish every moment spent with you.",
  "You're my best friend and my true love.",
  "Together, we are unstoppable.",
  "You are the poetry in my heart.",
  "I'm grateful to have you by my side.",
  "Your smile is my favorite sight.",
  "You make ordinary moments extraordinary.",
  "You're the calm in my chaos.",
  "Just thinking of you makes me smile.",
  "You're the missing piece I didn't know I needed.",
  "You make love feel easy and real.",
  "You have the kindest soul I've ever known.",
  "Every time I look at you, I feel lucky.",
  "You make my life better in every way.",
  "When I'm with you, time stands still.",
  "You are my today and all of my tomorrows.",
  "My heart feels safe with you.",
  "You are the dream I never want to wake up from.",
  "You're the melody in my favorite song.",
  "I see my future every time I look into your eyes.",
  "You're my first thought in the morning and my last at night.",
  "Loving you is the easiest choice I've ever made.",
  "You turn my world into something beautiful.",
  "With you, I've found my forever.",
  "You inspire me to be the best version of myself.",
  "You're the reason my heart smiles.",
  "Home is wherever I'm with you.",
  "You are the love I never knew I was searching for.",
  "You make my heart sing with joy.",
  "You are the reason I believe in magic.",
  "You are my greatest adventure.",
  "Your love is the anchor that keeps me grounded.",
  "No words can truly capture what you mean to me.",
  "You are the most beautiful part of my soul.",
  "In your arms, I've found peace and purpose.",
  "Loving you feels like breathing — natural and essential.",
  "You bring out the light in every part of me.",
  "I didn't believe in fate until I met you.",
  "You're not just part of my life — you're the best part.",
  "You're my favorite person to do everything and nothing with.",
  "With you, even silence is comfortable.",
  "You're the heartbeat I never want to lose.",
  "My love for you only grows deeper with time.",
  "You're the magic I didn't know I was missing.",
  "You've taught me what real love looks like.",
  "You make the hard days easier and the good days even better.",
  "You love me in ways I never thought possible.",
  "When I look at you, I see everything I've ever wanted.",
  "You're the kind of love that only happens once in a lifetime.",
  "You've turned my life into a beautiful love story.",
  "Every road I take, I want it to lead back to you.",
  "You've made my heart your home, and it's never felt warmer.",
  "Being loved by you is the greatest gift I've ever received.",
  "You're my always, my everything, my only.",
  "I still get butterflies when I hear your name.",
  "Your presence alone brings me peace.",
  "I'd choose you, in every life, every time.",
  "You are love, in its purest form.",
  "You're my reason, my rhythm, my rhyme.",
  "Loving you is like a beautiful song I never want to stop playing.",
  "You've filled the gaps I didn't know were there in my heart.",
  "You are the dream I never want to wake up from.",
  "You make every day feel like a new beginning.",
  "You are the reason I believe in soulmates.",
  "Your love is the light that guides me through the darkest times.",
  "You are the calm in my storm, the peace in my chaos.",
  "You make my heart feel at home, no matter where we are.",
  "You are the love story I never want to end.",
  "You are the reason I wake up with a smile every day.",
  "You are the spark that ignites my passion for life.",
  "You are the reason I believe in forever.",
  "You are the love that makes my heart sing.",
  "You are the reason I look forward to tomorrow.",
  "You are the love that makes every moment worth living.",
  "You are the reason I believe in magic and miracles.",
  "You are the love that makes my soul dance.",
  "You are the reason I feel alive.",
  "You are the love that makes my heart soar.",
  "You are the reason I believe in the beauty of love.",
  "You are the love that makes my life complete.",
  "You are the reason I believe in second chances.",
  "You are the love that makes every day feel like a gift.",
  "You are the reason I believe in the power of love.",
  "You are the love that makes my heart sing.",
  "Your love is the spark that lights my soul.",
  "No matter where life takes us, I'll always find my way to you.",
  "You make me feel seen, heard, and deeply loved.",
  "With you, I've discovered what happiness truly feels like.",
  "Even in a room full of people, my eyes search only for you.",
  "You are the warmth in my coldest moments.",
  "Being in your arms feels like the safest place on earth.",
  "You love me in ways I didn't know I needed.",
  "I could search the world and never find someone like you.",
  "You're the reason I believe that love can last forever.",
  "You're not just part of my life, you *are* my life.",
  "I never knew love could feel this effortless until I met you.",
  "Your love has healed parts of me I didn't know were broken.",
  "I didn't know what I was missing until you walked in.",
  "When I'm with you, I forget the rest of the world exists.",
  "You've painted my life in colors I didn't know existed.",
  "No poem, no song, no story could fully express how much I love you.",
  "Your voice is my favorite sound in the universe.",
  "Even the stars envy the way you shine in my life.",
  "You're the kind of miracle I never dared pray for.",
  "You've turned the ordinary into something extraordinary.",
  "There's no version of my future that doesn't include you.",
  "You fill my heart in ways words can never describe.",
  "You're the peace to my storm, the calm to my chaos.",
  "Your love is the rhythm that keeps my heart in tune.",
  "Just one look from you and the whole world fades away.",
  "Forever doesn't seem long enough with you.",
  "You make my world feel like a fairytale — one I never want to end.",
  "You're the one I'd choose in a thousand lifetimes.",
  "You're everything I hoped for and more than I ever dreamed."
];
